apiVersion: v1
kind: ConfigMap
metadata:
  name: commondb-config
  namespace: 5gc-udr
data:
  odbc.ini: |
    [confDB_master]
    Driver=MariaDB ODBC 3.0 Driver
    DATABASE=UDR_CFG
    DESCRIPTION=MariaDB via ODBC
    SERVER= commondb-sts-0.commondb.5gc-commondb-sts.svc.cluster.local
    UID=udr
    PASSWORD=udr
    PORT=3306

    [confDB_slave]
    Driver=MariaDB ODBC 3.0 Driver
    DATABASE=UDR_CFG
    DESCRIPTION=MariaDB via ODBC
    SERVER= commondb-sts-1.commondb.5gc-commondb-sts.svc.cluster.local
    UID=udr
    PASSWORD=udr
    PORT=3306

    [metaDB_master]
    Driver=MariaDB ODBC 3.0 Driver
    DATABASE=UDR_META
    DESCRIPTION=MariaDB via ODBC
    SERVER= commondb-sts-0.commondb.5gc-commondb-sts.svc.cluster.local
    UID=udr
    PASSWORD=udr
    PORT=3306

    [metaDB_slave]
    Driver=MariaDB ODBC 3.0 Driver
    DATABASE=UDR_META
    DESCRIPTION=MariaDB via ODBC
    SERVER= commondb-sts-1.commondb.5gc-commondb-sts.svc.cluster.local
    UID=udr
    PASSWORD=udr
    PORT=3306

    [subsDB_master]
    Driver=MariaDB ODBC 3.0 Driver
    DATABASE=UDR_SUBS
    DESCRIPTION=MariaDB via ODBC
    SERVER= commondb-sts-0.commondb.5gc-commondb-sts.svc.cluster.local
    UID=udr
    PASSWORD=udr
    PORT=3306

    [subsDB_slave]
    Driver=MariaDB ODBC 3.0 Driver
    DATABASE=UDR_SUBS
    DESCRIPTION=MariaDB via ODBC
    SERVER= commondb-sts-1.commondb.5gc-commondb-sts.svc.cluster.local
    UID=udr
    PASSWORD=udr
    PORT=3306

